"""empty message

Revision ID: 88ad4b4af1df
Revises: 1f18240624ab
Create Date: 2018-08-08 21:27:26.083188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88ad4b4af1df'
down_revision = '1f18240624ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banner', 'name')
    # ### end Alembic commands ###
