"""empty message

Revision ID: 979a49b4671b
Revises: 4edd44ede5a3
Create Date: 2018-08-08 21:10:28.677926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979a49b4671b'
down_revision = '4edd44ede5a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banner',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('link_url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('priority')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banner')
    # ### end Alembic commands ###
