"""empty message

Revision ID: f2ddebd6d6fa
Revises: 6bef196526cc
Create Date: 2018-08-04 17:34:56.138147

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2ddebd6d6fa'
down_revision = '6bef196526cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_role', sa.Column('permissions', sa.Integer(), nullable=False))
    op.drop_column('cms_role', 'permission')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_role', sa.Column('permission', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('cms_role', 'permissions')
    # ### end Alembic commands ###
